### ISSUE TITLE
How to use on multidimensional time series data

### ISSUE THREAD

**Issue by cadrev** [maminian/caterpillar_mset#2]
I'm a bit confused, is the library able to accomodate multi-dimensional time series data? Or it's just 1D?

**Comment by maminian** [comment]
Yes, the code should work on multi-dimensional time series. The examples with pictures are motivated by scalar time series because that was the main application I was using when developing the code.

But, if you look at the examples you'll notice that time-delayed embedding is used to map the scalar time series to R^3, after which MSET is applied. If you already have multiple variable, you can just bypass the time-delayed embedding step and directly use the next steps.

But, please let me know if you're running in to errors.
